### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by jessebye**
Forgot to bump the version in last PR

### CODE REVIEW

**Comment by charles-001** [comment]
@jessebye - I just actually found a problem with your PR #10. If I have a path like `prod/backups/*/mysqldump`, your code no longer shows any backups. Can you make your code have wildcardable paths like my original code did? The `*` in that path could be a cluster, hostname, etc. I currently use that type of path for my backups.

**Comment by jessebye** [comment]
Sure, I can take a look.

**Comment by charles-001** [comment]
Here's the config I use:
```ini
[main]
bucket = my_bucket
path = prod/backups
environment = prod
source = s3

[prod/backups/*/mysqldump]
hourly = 48
daily = 7
weekly = 4
monthly = 6
yearly = 1
include_list =
exclude_list =

[prod/backups/*/xtrabackup]
hourly = 48
daily = 7
weekly = 4
monthly = 6
yearly = 1
include_list =
exclude_list =
```

**Comment by jessebye** [comment]
@charles-001 what do the contents of those folders `mysqldump` or `xtrabackup` look like? do they have timestamped folders or files inside them?

**Comment by jessebye** [comment]
nvm, I think I got it working 😄

**Comment by charles-001** [comment]
Just to clarify, they're files :)

**Pull request closed without merging**
