### PR TITLE
fix: optimize deletion

### PR DESCRIPTION
**Pull request by jessebye**
Optimize the deletion by reusing the Bucket object, and make the exceptions more sensible.

@charles-001 I couldn't find a way to force the deletion to fail 🤔 do you have any idea how to force this for testing?

### CODE REVIEW

**Comment by charles-001** [comment]
Honestly, you could just append a "1" to the filename to see how it fails. Can you do that?

**Comment by charles-001** [comment]
Really? It says it successfully deleted on a file that doesn't exist? Strange...

**Comment by jessebye** [comment]
Ah yeah, found evidence of this in the [s3 API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html):

> Note that if the object specified in the request is not found, Amazon S3 returns the result as deleted.

**Comment by charles-001** [comment]
Hm... Can you try a read-only access key?

**Comment by jessebye** [comment]
That worked 😁 

```
11-21-2024 12:43:19 [ERROR] Failed to delete backup backups-test/2024-11-19.sqls: AccessDenied - User: arn:aws:sts::xxxxxxxx:assumed-role/AWSReservedSSO_ViewOnlyAccess_xxxxxxxxxxx/jbye is not authorized to perform: s3:DeleteObject on resource: "arn:aws:s3:::my-bucket/backups-test/2024-11-19.sqls" because no identity-based policy allows the s3:DeleteObject action
11-21-2024 12:43:19 [ERROR] Failed to delete backup backups-test/2024-11-17.sqls: AccessDenied - User: arn:aws:sts::xxxxxxxx:assumed-role/AWSReservedSSO_ViewOnlyAccess_xxxxxxxxxxxx/jbye is not authorized to perform: s3:DeleteObject on resource: "arn:aws:s3:::my-bucket/backups-test/2024-11-17.sqls" because no identity-based policy allows the s3:DeleteObject action
...
╭─────────────────┬───────────────────────────┬────────────┬───────────────────────────────────────────────╮
│ Backup          │ Timestamp                 │ Size       │ Status                                        │
├─────────────────┼───────────────────────────┼────────────┼───────────────────────────────────────────────┤
│ 2024-11-16.sql  │ 2024-11-16 00:00:00-08:00 │ 0.00 B     │ Deleted (failed)                              │
│ 2024-11-17.sql  │ 2024-11-17 00:00:00-08:00 │ 0.00 B     │ Deleted (failed)                              │
│ 2024-11-18.sql  │ 2024-11-18 00:00:00-08:00 │ 0.00 B     │ Deleted (failed)                              │
│ 2024-11-19.sql  │ 2024-11-19 00:00:00-08:00 │ 0.00 B     │ Deleted (failed)                              │
│ 2024-11-20.sql  │ 2024-11-20 00:00:00-08:00 │ 0.00 B     │ Deleted (failed)                              │
│ 2024-11-21.sql  │ 2024-11-21 00:00:00-08:00 │ 0.00 B     │ Preserving (matches 'daily' retention period) │
╰─────────────────┴───────────────────────────┴────────────┴───────────────────────────────────────────────╯

11-21-2024 12:43:19 [CRITICAL] Failed to delete backups!
```

**Comment by charles-001** [comment]
Nice! Good job on that. 1 question... should it stop processing after the first batch if there's any failure like it's currently doing or print them all out and then fail? `raise Exception("Failed to delete backups!")` is what will stop it after the first batch of `1000`

**Comment by jessebye** [comment]
Personally, I'd probably prefer a fast failure, especially if it's trying to delete thousands of files.

**Comment by charles-001** [comment]
Sounds good to me. Thanks for your contribution as always!

**Comment by charles-001** [comment]
@jessebye New version is now in PyPi! Just curious, have you tested the batch deleting with more than 1000?

**Comment by jessebye** [comment]
Excellent, thank you! I have tested delete for over 1000 objects, but only for the s3 only prefixes mode. It should be pretty easy to test the other scenario though... I may be able to test it out tomorrow.

**Comment by charles-001** [comment]
Sounds good, just lmk. You seem to have the environment for testing this thoroughly :)

**Comment by charles-001** [comment]
Looks good! Thank you

**Pull request merged**
